export const userTypes={
    USER_SIGNPHONE:"USER_SIGNPHONE",
    USER_AUTHENTICATION:"USER_AUTHENTICATION",
    USER_CREATE:"USER_CREATE",
    USER_LOGOUT:"USER_LOGOUT",
    USER_LOGIN: "USER_lOGIN",
}